### ISSUE TITLE
Pin Kubernetes versions in Terraform.

### ISSUE THREAD

**Issue by jondkent** [kubernetes-simulator/simulator#70]
**Feature statement**
Currently the terraform cloud init configuration installs the latest version of kubernetes (kubeadm, kubectl etc).

Simulator should be able to specify the version of Kubernetes that is to be installed for the scenario, defaulting to the latest if none is defined.

**Issue**

At present simulator first stands up the infrastructure, which includes installing kubernetes (via kubeadm), using a cloud-init script on the nodes. Then the scenario is applied.  To specify a version of kubernetes this workflow is incorrect.

**Proposed approach**

Change the workflow order from `simulator infra create` and `simulator scenario launch` to just `simulator scenario launch`.  This single command will action:

- Verify if existing infrastructure exists, destroy if it does (maybe with a verification input from user first)
- Pass Kubernetes version to Terraform (with a Terraform default is none supplied)
- Terraform creates node cloud-init yaml files from jinja templates to apply kubernetes version
- Create infrastructure
- Deploy scenario

**Comment by raoulmillais** [comment]
I don't think we remove steps available to the user because they are helpful for development:

* Testing individiual parts
* Iterating quickly on scenarios
* working on subsections

As for changing the recommended default, to do an `infra create` as part of `scenario launch`, I think we should evaluate this in the context of the coming scoring and cluster reset work - we now rely on the bastion to keep track of state.

**Comment by jondkent** [comment]
I think we should leave the ability to run `simulator create infra` for testing/iterating for sure, but have the approach outlined for users to run scenarios

**Comment by jondkent** [comment]
Closing this as presently there are no scenarios that require it. Reopen should that situation change
